import { runAmiAction, type AmiActionResult } from "./ami-connection";

// Read-only AMI surface for the MCP server.
//
// THE THREAT THIS FILE EXISTS TO CLOSE: AMI's `Command` action runs an
// arbitrary Asterisk CLI command. A tool whose input schema is
// `{ command: string }` would hand an LLM (and anything that can influence
// that LLM — a caller ID, a voicemail transcript, a CRM note) full Asterisk
// CLI access: `database show` dumps every SIP secret, `module unload` takes
// the PBX offline. That is exactly the AMI command-injection class another
// workstream is fixing in the app layer, and recreating it here through a
// "convenience" free-text parameter would be worse, not better, because
// nothing else sits between the model and the socket.
//
// So: the tool-facing input is an ENUM KEY, never a command string. The key
// indexes into the frozen table below; the command text is a literal in this
// file and can only be changed by editing this file. There is deliberately
// no escape hatch, no "advanced" passthrough, and no template interpolation
// except the one narrowly-validated endpoint id below.

export const READ_COMMANDS = {
  pjsip_show_endpoints: "pjsip show endpoints",
  core_show_channels: "core show channels",
  queue_show: "queue show",
  core_show_version: "core show version",
} as const;

export type ReadCommandKey = keyof typeof READ_COMMANDS;

export const READ_COMMAND_KEYS = Object.keys(READ_COMMANDS) as [ReadCommandKey, ...ReadCommandKey[]];

// `pjsip show endpoint <id>` is the one read that takes a parameter. PJSIP
// endpoint ids in this deployment are extension numbers generated by
// src/lib/pjsip-config.ts (\d{3,6}) plus the static trunk names from
// pjsip-base.conf, so this pattern is generous relative to what actually
// exists while still admitting nothing that could alter the command's
// meaning: no whitespace (which would append a second CLI argument), no
// shell metacharacters, no CR/LF.
const ENDPOINT_ID = /^[A-Za-z0-9_-]{1,64}$/;

export function assertEndpointId(endpointId: string): void {
  if (!ENDPOINT_ID.test(endpointId)) {
    throw new Error(
      `Invalid PJSIP endpoint id "${endpointId}". Must be 1-64 characters of [A-Za-z0-9_-] — no spaces or punctuation.`
    );
  }
}

/**
 * Build the CLI text for a read. Exported separately from `runReadCommand`
 * so the mapping from (enum key, optional endpoint id) to literal command
 * text is unit-testable without an Asterisk instance — that mapping is the
 * whole security boundary, so it is the thing worth testing.
 */
export function buildReadCommand(key: ReadCommandKey, endpointId?: string): string {
  if (endpointId !== undefined) {
    if (key !== "pjsip_show_endpoints") {
      throw new Error(`Command "${key}" does not accept an endpoint id.`);
    }
    assertEndpointId(endpointId);
    return `pjsip show endpoint ${endpointId}`;
  }
  return READ_COMMANDS[key];
}

/** Run one allowlisted read and return the CLI output as plain text. */
export async function runReadCommand(key: ReadCommandKey, endpointId?: string): Promise<string> {
  const command = buildReadCommand(key, endpointId);
  const result: AmiActionResult = await runAmiAction({ Action: "Command", Command: command });
  const text = result.output.join("\n").trim();
  return text || result.headers.Message || "(no output)";
}
